function parc_GWC=parc_mapback(parc_SLIC,parc_MSC)
% Map the clustering results based on supervoxels back onto the brain.
% Input:
%     img_parc_slic, supervoxels generated by SLIC
%     label, clustering results by aggregating supervoxels
% Output:
%     img_parc, the final parcellation result

load parc_graymatter.mat;
labels=parc_SLIC(ind_gray); 
sC=unique(labels); % all labels, C for cluster
nC=length(sC); % the actual cluster number
tmp=parc_SLIC(:);
temp=zeros(size(tmp));
for iC=1:nC
    cC=sC(iC);
    temp(tmp==cC)=parc_MSC(iC);
end
temp=reshape(temp,size(parc_SLIC));
parc_GWC=temp;
